#version: '3.3'

services:
    minimusdb:
        image: mysql:8.0.25
        container_name: minimusdb
        restart: always
        environment:
            MYSQL_DATABASE: 'minimus'
            MYSQL_USER: 'liono'
            MYSQL_PASSWORD: 'thundercats'
            MYSQL_ROOT_PASSWORD: 'threeblindmice'
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d/:ro
            - /opt/db/minimusdb:/var/lib/mysql
        ports:
            - 3306:3306
    web:
        container_name: minimus
        image: minimus-bundle:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./adobe:/var/www/html/adobe
            - ./banking:/var/www/html/centralbank
        environment:
            - APACHE_LOG_DIR=/var/log/apache2
        depends_on:
            - minimusdb
