version: '3.8'

services:
    tethysdb:
        image: mysql:8.0.25
        container_name: minimusdb
#        tty: true
        restart: always
        environment:
            MYSQL_DATABASE: 'minimus'
            MYSQL_USER: 'liono'
            MYSQL_PASSWORD: 'thundercats'
            MYSQL_ROOT_PASSWORD: 'threeblindmice'
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d/:ro
            - /opt/db/minimusdb:/var/lib/mysql
        ports:
            - 3306:3306
    web:
        container_name: minimus
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
        environment:
            - APACHE_LOG_DIR=/var/log/apache2
#        extra_hosts:
#            - "tethys:${PUBLIC_IP}"
        depends_on:
            - minimusdb